"""Cleanup command for agent interactive mode."""
import json

from pathlib import Path

from .base import Command
from agent_core import to_windows_path

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from agent import Agent


class CleanupCommand(Command):
    """Show unreferenced files and reference graph."""

    @property
    def name(self) -> str:
        return "cleanup"

    @property
    def help_text(self) -> str:
        return "cleanup             - Show unreferenced files and reference graph"

    async def execute(self, args: list[str], agent: 'Agent') -> bool:
        ws = agent.workspace
        ws = to_windows_path(ws)
        ws_path = Path(ws)

        if not ws_path.exists():
            print(f"Workspace not found: {ws_path}")
            return True

        print(f"\nScanning {ws_path} for generated files...")

        generated_files = {}
        manifest_file = ws_path / ".generated_manifest.json"
        if manifest_file.exists():
            with open(manifest_file, "r", encoding="utf-8") as mf:
                generated_files = json.load(mf)
            print(f"  Manifest: {len(generated_files)} previously generated files")

        all_files = {}
        for fp in ws_path.rglob("*"):
            if fp.is_file() and ".git" not in str(fp) and "__pycache__" not in str(fp):
                rel = str(fp.relative_to(ws_path)).replace("\\", "/")
                all_files[rel] = {"size": fp.stat().st_size, "generated": rel in generated_files}

        references: dict[str, set[str]] = {f: set() for f in all_files}
        for fname in all_files:
            fp = ws_path / fname
            try:
                content = fp.read_text(encoding="utf-8", errors="ignore")
                for other in all_files:
                    if other != fname and other in content:
                        references[other].add(fname)
            except Exception as exc:
                print(f"  Warning: could not read {fname}: {exc}")

        active_candidates = [f for f in all_files if f.startswith("project_") and f.endswith(".md")]
        active = set()
        for root in active_candidates:
            queue = [root]
            while queue:
                f = queue.pop()
                if f in active:
                    continue
                active.add(f)
                for ref_by in references.get(f, set()):
                    queue.append(ref_by)

        for f in active_candidates:
            active.add(f)

        unreferenced = [f for f in all_files if f not in active and f.endswith((".md", ".py", ".json"))]
        external = [f for f in unreferenced if f in generated_files]

        print(f"\n  Total files scanned: {len(all_files)}")
        print(f"  Active (referenced): {len(active)}")
        print(f"  Unreferenced: {len(unreferenced)} ({'generated by agent' if external else 'external'})")

        if unreferenced:
            print("\n  Unreferenced files:")
            for f in sorted(unreferenced):
                tag = " [generated]" if f in generated_files else ""
                print(f"    {f} ({all_files[f]['size']} bytes){tag}")

            print("\n  Use --delete to remove them, or add to .protected to keep.")
        else:
            print("  No unreferenced files found.")

        print("\n  Reference graph (active files):")
        for f in sorted(active):
            refs = references.get(f, set())
            if refs:
                print(f"    {f} <- referenced by: {', '.join(sorted(refs))}")

        return True