# ... (previous lines 1-92) ...

    # Line 93: Added missing closing quote to properly terminate the string literal
    if cleaned.startswith("expected_prefix"):  # Replace with your actual target string

# ... (remaining lines 94+) ...